"""modified user table again

Revision ID: 0d03bea8bfa8
Revises: 7a4ec8383240
Create Date: 2020-01-26 01:30:56.549300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d03bea8bfa8'
down_revision = '7a4ec8383240'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=200), nullable=True))
    # ### end Alembic commands ###
