"""modified user table again3

Revision ID: 14624cf8f70a
Revises: 0d03bea8bfa8
Create Date: 2020-01-26 01:36:48.278275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14624cf8f70a'
down_revision = '0d03bea8bfa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_column('email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=200), nullable=True))
    # ### end Alembic commands ###
